import React from 'react'

export const metadata = {
    title: 'Sanity Studio',
    description: 'Generated by create next app',
  }
  
  export default function LayoutAdmin({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
      <body>
        {children}
      </body>
    </html>
    )
  }

// export default layout