'use client'

import config from '@/sanity.config'
import {NextStudio} from 'next-sanity/studio'

export const metadata = {
    title: 'Sanity Studio',
    description: 'Generated by create next app',
  }

export default function AdminPage(){
    return <NextStudio config={config} />
}