import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-gray-950`}>
        <main className="max-w-7xl mx-auto min-h-screen text-black dark:text-white">
          <Navbar />
          <div className='p-8'>{children}</div>
        </main>
      </body>
    </html>
  )
}
